### ISSUE TITLE
Using jwt-decode beta with node10 module resolution

### ISSUE THREAD

**Issue by frederikprijck** [auth0/jwt-decode#222]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When we use jwt-decode's beta in a project that uses `node10` for the module strategy, it allowas for the following imports:

```
import { jwtDecode } from 'jwt-decode';
import { jwtDecode as jwtDecode2 } from 'jwt-decode/build/cjs/index';
import { jwtDecode as jwtDecode3 } from 'jwt-decode/build/esm/index';
```

Even though this could be considered normal, I wonder if we can improve this for the situation where node10 is used as a module resolution strategy.

### Reproduction

- mkdir typescript-project
- cd typescript-project
- npm i typescript
- npx tsc --init
- touch index.ts

Update index.ts to add

```ts
import { jwtDecode } from 'jwt-decode';
import { jwtDecode as jwtDecode2 } from 'jwt-decode/build/cjs/index';
import { jwtDecode as jwtDecode3 } from 'jwt-decode/build/esm/index';
```

You will see it allows for these imports, unless you set moduleResolution to node16.

### jwt-decode version

latest beta

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
@jonkoops, just cc'ing you FYI as you were heavily involved in setting this up. I wonder if we can avoid this by not having individual types for both ESM and CJS, as they are identical anyway.

That would ensure we can only do
```
import { jwtDecode } from 'jwt-decode';
import { jwtDecode as jwtDecode2 } from 'jwt-decode/build/types/index';
```
which might make more sense.

Will have a look.

**Comment by frederikprijck** [comment]
According to https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md, we should not have a single type declarations file. We have been here before and we went with two different type declarations files for the exact same reason.

I assume there isn't much we can do about this but leave it as is.

**Comment by jonkoops** [comment]
Since we don't support any version of Node.js before 18 I don't think this will be an issue. Even though the user could set the `node10` module resolution strategy, that code will not run properly in Node.js 16 and up.

The reason for this is that starting with Node.js 16 (AFAIK), it will respect the `"exports"` field in the package file, which will prevent this kind of access. As per the Node.js [documentation](https://nodejs.org/api/packages.html#package-entry-points):

> The `"exports"` provides a modern alternative to `"main"` allowing multiple entry points to be defined, conditional entry resolution support between environments, and **preventing any other entry points besides those defined in `"exports"`**.

So from what I can tell the `node10` preset only exists to provide compatibility with historical versions of Node.js that might have these sort of 'illegal' imports going on. Which is fine, as long as they run on older versions that do not respect the `"exports"` field.

>  I wonder if we can avoid this by not having individual types for both ESM and CJS, as they are identical anyway.

Like you mentioned, this will then break the `node16` resolution strategy, as it needs to have distinct types. I think we should keep them to keep things compatible going forward.

@frederikprijck somewhat related to this, perhaps we should make a clean break and simply roll with the `"exports"` field only? So essentially remove the `"main"`, `"module"` and `"types"` fields. They might still be used, but it could also be the case that most have a modern enough bundler to make things work.

I feel more comfortable shipping without them, rather than pushing them, knowing they might be incorrect. Also adding them back in a quick patch release if we do get issue reports is rather trivial.

**Comment by frederikprijck** [comment]
> Since we don't support any version of Node.js before 18 I don't think this will be an issue. Even though the user could set the node10 module resolution strategy, that code will not run properly in Node.js 16 and up.

Based on my tests, if you run `tsc --init`, it omits moduleResolution and defaults to 10.

**Comment by frederikprijck** [comment]
Yeah having tested this in a project that gets created using `tsc --init`, we get the following error when we omit `main`, `module` and `types` properties in the package.json

![image](https://github.com/auth0/jwt-decode/assets/2146903/b721400c-487a-420b-b41d-d7626f3f97d4)

So as long as node16 isnt the default, I think we should keep it.

**Comment by jonkoops** [comment]
> We shipped node-auth0 with the same config and havent had any issues yet.

If this is battle tested then I feel a little more comfortable shipping like this, it's mostly there to guarantee backwards compatibility. This might be something to re-consider in the future when the platform as a whole has moved on, but if it helps prevent real issues for users let's keep it this way.

To answer your original question, I kind of have to agree that there is no real way of providing a better experience for users of `node10`. These kind of imports are entirely valid in those versions of Node.js, although the TypeScript compiler perhaps should do a better job at warning users of this potential pitfall.

Should we close this issue then? Considering there is very little we can do.

**Comment by jonkoops** [comment]
@frederikprijck I found a relevant issue on the TypeScript project that might be relevant for this discussion:  https://github.com/microsoft/TypeScript/issues/55104

**Comment by frederikprijck** [comment]
Thanks for sharing.

Not sure it's related, as it does work in node10, it just allows for all kinds of imports and IDE's get confused.

That said, happy to close this yes, thanks for the input!
