### ISSUE TITLE
Remove eval function

### ISSUE THREAD

**Issue by euharrison** [auth0/jwt-decode#24]
Hi! I received an alert from my host that the script has a suspicious `eval()` code, this is the alert:

![12637151_955493134530531_662725185_o](https://cloud.githubusercontent.com/assets/557598/13178500/4bf57868-d706-11e5-8743-bf49c55f5a8b.jpg)

Debugging it I found that this code came from here https://github.com/auth0/jwt-decode/blob/master/build/jwt-decode.js#L56

Do you think that we have a workaround with this eval function?

**Comment by jfromaniello** [comment]
It is using eval as a fallback when there is no JSON support in the browser... maybe we can remove that since it seems is already supported in every major browser:

http://caniuse.com/#feat=json

and if the developer really needs to support old browser he can polyfill on their own before loading this library.

**Comment by sandstrom** [comment]
@jfromaniello sounds like a great solution! JSON is *widely* supported, and there are good polyfills available for those rare, old browsers.

**Comment by jfromaniello** [comment]
thanks!
