### ISSUE TITLE
error cannot find module jwt-decode.esm.js

### ISSUE THREAD

**Issue by satyaprakash-yadav** [auth0/jwt-decode#389]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

./node_modules/jwt-decode/build/jwt-decode.esm.js
Error: ENOENT: no such file or directory, open 'C:\Users\Public\Documents\Full Stack Applications\Mern Applications\Slack Clone\slack-app\node_modules\jwt-decode\build\jwt-decode.esm.js'

Import trace for requested module:
./node_modules/jwt-decode/build/jwt-decode.esm.js
./node_modules/convex/dist/esm/browser/sync/authentication_manager.js
./node_modules/convex/dist/esm/browser/sync/client.js
./node_modules/convex/dist/esm/browser/index.js
./node_modules/convex/dist/esm/react/client.js
./node_modules/convex/dist/esm/react/index.js
./src/components/ConvexClientProvider.tsx

### Reproduction

![Screenshot (759)](https://github.com/user-attachments/assets/aa90b227-490e-4ec8-8677-d2574ec24fa6)

### jwt-decode version

^4.0.0

### Which browsers have you tested in?

Chrome

**Comment by jonkoops** [comment]
Looks like you are somehow importing a path from `jwt-decode` that was present in v3, but no longer exists in v4. Looking at the call stack this is required by the `convex` module. Not sure how, because `convex` doesn't have support for v4 (it's [still on v3](https://github.com/get-convex/convex-js/blob/4e4e416c981ef8936ebe45bdf727d03984b7d2de/package.json#L166)).

If you are overwriting the version of `jwt-decode`, don't, it will just break stuff. I can't really judge anything about this setup, but I can tell you this is not a bug in `jwt-decode`, and likely something specific about your setup.

**Comment by jonkoops** [comment]
Created a PR to upgrade this dependency under https://github.com/get-convex/convex-js/pull/15. For support I'd recommend you contact the `convex` folks.

**Comment by satyaprakash-yadav** [comment]
thank you so much for giving this information and i solved my bug
