### ISSUE TITLE
Add method to verify jwt-token

### ISSUE THREAD

**Issue by AuthorProxy** [auth0/jwt-decode#67]
It will useful to add some method to validate that all three segments of jwt is valid and can be decoded successfully, or additional check can be integrated into the main method, raising error if some of segments not valid

**Comment by jaredrsowers** [comment]
@mirez, not exactly true. 

As long as one of the asymmetrical algorithms is being used (almost always the case), all you need is the public key, not the private key. 

In fact, the OpenID Connect protocol provides an endpoint for getting said public key so that you can verify that the token was generated by the given provider.

**Comment by indeyets** [comment]
It's still a good idea to have such method

**Comment by Widcket** [comment]
Hi, for ID Token verification you can use the [idtoken-verifier](https://github.com/auth0/idtoken-verifier) library.

**Comment by soichih** [comment]
Re-itereating what @jaredrsowers said back in 2018.. jwt token can be validated as long as we have a public key, no?
